---
- name: install nginx 
  yum: 
    name: nginx
    state: latest

- name: start and enable nginx 
  service: 
    name: nginx
    state: started
    enabled: yes 

- name: sent nginx file config to remote server
  copy: 
    src: ../templates/nginx.conf
    dest: /etc/nginx/conf.d/nginx.wordpress.conf
    owner: nginx 
    group: nginx
    mode: '0755'

- name: restart nginx 
  service:
    name: nginx
    state: restarted

- name: add nginx to firewalld
  firewalld:
    port: 80/tcp
    permanent: yes 
    state: enabled 
    immediate: yes 


     

  

